version: "3.8"
services:
    nginx:
        image: nginx:latest
        env_file:
            - .env
        ports:
            - "80:80"
        volumes:
            - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
            - ./site1:/var/www/site1
        depends_on:
            - php
    php:
        build:
            context: ./docker/php
        env_file:
            - .env
        volumes:
            - ./site1:/var/www/site1
    database:
        image: postgres:${POSTGRES_VERSION:-15}-alpine
        ports:
            - "5432"
        environment:
            POSTGRES_DB: ${POSTGRES_DB:-app}
            # You should definitely change the password in production
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-!ChangeMe!}
            POSTGRES_USER: ${POSTGRES_USER:-app}
        volumes:
            - database_data:/var/lib/postgresql/data:rw
volumes:
    database_data: