version: "3.8"

services:
    nginx:
        image: nginx:latest
        env_file:
            - .env
        ports:
            - "80:80"
        volumes:
            - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
            - ./site1:/var/www/site1
        depends_on:
            - php

    php:
        build:
            context: ./docker/php
        env_file:
            - .env
        volumes:
            - ./site1:/var/www/site1
        depends_on:
            - database

    database:
        image: postgres
        environment:
            POSTGRES_DB: ${POSTGRES_DB}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        ports:
            - "5432"

    adminer:
        image: adminer
        ports:
            - "8080:8080"